config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/guest_login', to: 'sessions#guest'
  delete '/logout', to: 'sessions#destroy'
  get '/posts/category/:id', to: 'posts#category', as: 'posts_category'
  get '/posts/popular', to: 'posts#popular', as: 'popular_posts'
  get '/posts/search', to: 'posts#search', as: 'search_posts'
  post '/post/like/:id', to: 'likes#post_create', as: 'post_like'
  delete '/post/unlike/:id', to: 'likes#post_destroy', as: 'post_unlike'
  post '/comment/like/:id', to: 'likes#comment_create', as: 'comment_like'
  delete '/comment/unlike/:id', to: 'likes#comment_destroy', as: 'comment_unlike'
  get '/comment/like/sort', to: 'comments#like_sort', as: 'comment_like_sort'
  resources :users
  resources :posts, except: %i[index]
  resources :relationships, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :check_login
  before_action :set_post, only: %i[post_create post_destroy]
  before_action :set_comment, only: %i[comment_create comment_destroy]

  def post_create
    @like = current_user.likes.create(post_id: @post.id)
  end

  def post_destroy
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
  end

  def comment_create
    @like = current_user.likes.create(comment_id: @comment.id)
  end

  def comment_destroy
    @like = current_user.likes.find_by(comment_id: @comment.id)
    @like.destroy
  end

  private

  # before action

  def set_post
    @post = Post.find(params[:id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_comment_like.html.erb
<% if current_user.likes.find_by(comment_id: comment.id) %>
  <%= link_to comment_unlike_path(comment), method: :delete, remote: true, class: 'like' do %>
    <%= icon('fas', 'heart') %>
  <% end %>
<% else %>
  <%= link_to comment_like_path(comment), method: :post, remote: true, class: 'not-like' do %>
    <%= icon('far', 'heart') %>
  <% end %>
<% end %>

<span><%= comment.likes.length %></span>

app/views/likes/_post_like.html.erb
<% if current_user.likes.find_by(post_id: post.id) %>
  <%= link_to post_unlike_path(post), method: :delete, remote: true, class: 'like' do %>
    <%= icon('fas', 'heart') %>
  <% end %>
<% else %>
  <%= link_to post_like_path(post), method: :post, remote: true, class: 'not-like' do %>
    <%= icon('far', 'heart') %>
  <% end %>
<% end %>

<span><%= post.likes.length %></span>

app/views/likes/comment_create.js.erb
$("#comment-like-<%= @comment.id %>").html("<%= j(render 'comment_like', { comment: @comment }) %>");

app/views/likes/comment_destroy.js.erb
$("#comment-like-<%= @comment.id %>").html("<%= j(render 'comment_like', { comment: @comment }) %>");

app/views/likes/post_create.js.erb
$("#post-like-<%= @post.id %>").html("<%= j(render 'post_like', { post: @post }) %>");

app/views/likes/post_destroy.js.erb
$("#post-like-<%= @post.id %>").html("<%= j(render 'post_like', { post: @post }) %>");