config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/guest_login', to: 'sessions#guest'
  delete '/logout', to: 'sessions#destroy'
  get '/posts/category/:id', to: 'posts#category', as: 'posts_category'
  get '/posts/popular', to: 'posts#popular', as: 'popular_posts'
  get '/posts/search', to: 'posts#search', as: 'search_posts'
  post '/post/like/:id', to: 'likes#post_create', as: 'post_like'
  delete '/post/unlike/:id', to: 'likes#post_destroy', as: 'post_unlike'
  post '/comment/like/:id', to: 'likes#comment_create', as: 'comment_like'
  delete '/comment/unlike/:id', to: 'likes#comment_destroy', as: 'comment_unlike'
  get '/comment/like/sort', to: 'comments#like_sort', as: 'comment_like_sort'
  resources :users
  resources :posts, except: %i[index]
  resources :relationships, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  # User model
  belongs_to :user

  # Category model
  belongs_to :category

  # Comment model
  has_many :comments, dependent: :destroy

  # Like model
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  # validations
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 400 }
  validates :check, presence: true, inclusion: { in: [0, 1] }
  validates :status, presence: true, inclusion: { in: [0, 1] }

  # Get id of public posts
  def self.public_posts
    Post.where(status: 1).pluck(:id)
  end

  # Get posts containing keyword
  def self.search(keyword)
    Post.where(status: 1).where('title LIKE ? OR content LIKE ?', "%#{keyword}%", "%#{keyword}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_login, only: %i[new create show edit update destroy]
  before_action :check_contributor, only: %i[edit update destroy]

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def index
    @posts = Post.where(status: 1).page(params[:page]).per(20).order(created_at: :desc)
  end

  def popular
    posts_sorted = Post.where(status: 1).order(created_at: :desc).sort { |a, b| b.likes.count <=> a.likes.count }
    @posts = Kaminari.paginate_array(posts_sorted).page(params[:page]).per(20)
  end

  def search
    @search_params = params[:search]
    @posts = Post.search(@search_params).page(params[:page]).per(20).order(created_at: :desc)
  end

  def category
    @category = Category.find(params[:id])
    @posts = @category.posts.where(status: 1).page(params[:page]).per(20).order(created_at: :desc)
  end

  def show
    respond_to do |format|
      format.html do
        if current_user.posts.pluck(:id).include?(params[:id].to_i)
          @post = Post.find(params[:id])
          @comment = Comment.new
          @comments = @post.comments.page(params[:page]).per(20).order(created_at: :desc)
        elsif Post.public_posts.include?(params[:id].to_i)
          @post = Post.find(params[:id])
          @comment = Comment.new
          @comments = @post.comments.page(params[:page]).per(20).order(created_at: :desc)
        else
          redirect_to root_path
        end
      end
      format.js do
        post = Post.find(params[:id])
        @comments = post.comments.page(params[:page]).per(20).order(created_at: :desc)
      end
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to user_path(@post.user)
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :content,
      :category_id,
      :check,
      :status
    )
  end

  # before action

  # Check contributor is self
  def check_contributor
    @post = Post.find(params[:id])
    redirect_to root_path unless current_user?(@post.user)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_category_menu.html.erb
<div class="category-menu">
  <span class="menu-title">カテゴリー別<%= icon('fas', 'caret-down') %></span>
  <div class="sub-menu">
    <ul>
      <li><%= link_to 'お父さん・お母さん', posts_category_path(1), class: 'menu menu1' %></li>
      <li><%= link_to 'お兄ちゃん・お姉ちゃん', posts_category_path(2), class: 'menu menu2' %></li>
      <li><%= link_to '弟・妹', posts_category_path(3), class: 'menu menu3' %></li>
      <li><%= link_to 'おじいちゃん・おばあちゃん', posts_category_path(4), class: 'menu menu4' %></li>
      <li><%= link_to '旦那さん・奥さん', posts_category_path(5), class: 'menu menu5' %></li>
      <li><%= link_to '息子・娘', posts_category_path(6), class: 'menu menu6' %></li>
      <li><%= link_to '孫', posts_category_path(7), class: 'menu menu7' %></li>
      <li><%= link_to '彼氏・彼女', posts_category_path(8), class: 'menu menu8' %></li>
      <li><%= link_to '友達', posts_category_path(9), class: 'menu menu9' %></li>
      <li><%= link_to 'その他', posts_category_path(10), class: 'menu menu10' %></li>
    </ul>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <div class="form-parts">
    <%= f.label :title, "タイトル" %>
    <span class="required">必須</span>
    <%= f.text_field :title, required: true %>
    <% if @post.errors.include?(:title) %>
      <p class="error-message"><%= @post.errors.full_messages_for(:title).first %></p>
    <% end %>
  </div>

  <div class="form-parts">
    <%= f.label :category_id, "誰に対して感謝を伝えたいですか？" %>
    <span class="required">必須</span>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
    <% if @post.errors.include?(:category_id) %>
      <p class="error-message"><%= @post.errors.full_messages_for(:category_id).first %></p>
    <% end %>
  </div>

  <div class="form-parts">
    <%= f.label :content, "内容" %>
    <span class="required">必須</span>
    <%= f.text_area :content, required: true %>
    <% if @post.errors.include?(:content) %>
      <p class="error-message"><%= @post.errors.full_messages_for(:content).first %></p>
    <% end %>
  </div>

  <div class="form-parts">
    <%= f.label :check, "感謝の気持ちは伝えましたか？" %>
    <span class="required">必須</span>
    <div class="check">
      <%= f.radio_button :check, '1', required: true %>
      <%= f.label :check, "はい", value: 1 %>
      <%= f.radio_button :check, '0', required: true %>
      <%= f.label :check, "まだです", value: 0 %>
    </div>
    <p class="explanation">「はい」を選択すると<i class="fas fa-star"></i>がつきます。（他のユーザーからは見えません）</p>
    <% if @post.errors.include?(:check) %>
      <p class="error-message"><%= @post.errors.full_messages_for(:check).first %></p>
    <% end %>
  </div>

  <div class="form-parts">
    <%= f.label :status, "公開・非公開設定" %>
    <span class="required">必須</span>
    <div class="status">
      <%= f.radio_button :status, '1', required: true %>
      <%= f.label :status, "公開する", value: 1 %>
      <%= f.radio_button :status, '0', required: true %>
      <%= f.label :status, "公開しない", value: 0 %>
    </div>
    <% if @post.errors.include?(:status) %>
      <p class="error-message"><%= @post.errors.full_messages_for(:status).first %></p>
    <% end %>
  </div>

  <button class="btn m-btn submit"><%= yield(:button_text) %><i class="fas fa-paper-plane"></i></button>
<% end %>

app/views/posts/_post.html.erb
<% posts.each do |post| %>
  <div class="post">
    <span class="category category-color<%= post.category.id %>"><%= post.category.name %></span>
    <h2 class="title"><%= post.title.truncate(24) %></h2>
    <% if post.content.length > 76 %>
      <p class="content"><%= post.content.slice(0..75) %>...</p>
    <% else %>
      <p class="content"><%= post.content.slice(0..75) %></p>
    <% end %>
    <a href="/posts/<%= post.id %>" class="details">詳細を見る</a>
    <div class="flex">
      <div class="comment-like">
        <span class="comment">
          <%= icon('fas', 'comment-dots') %>
          <%= post.comments.length %>
        </span>
        <span class="like">
          <%= icon('fas', 'heart') %>
          <%= post.likes.length %>
        </span>
      </div>
      <a href="/users/<%= post.user.id %>">
        <% if post.user.image? %>
          <%= image_tag post.user.image.url, alt: 'アイコン画像', width: '50', height: '50' %>
        <% else %>
          <img alt="アイコン画像" src="/assets/default.png" width="50" height="50">
        <% end %>
      </a>
    </div>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <div class="post">
    <span class="category category-color<%= post.category.id %>"><%= post.category.name %></span>
    <% if current_user?(post.user) %>
      <% if post.check == 1 %>
        <h2 class="title"><i class="fas fa-star"></i><%= post.title.truncate(23) %></h2>
      <% else %>
        <h2 class="title"><%= post.title.truncate(23) %></h2>
      <% end %>
    <% else %>
      <h2 class="title"><%= post.title.truncate(23) %></h2>
    <% end %>
    <% if post.content.length > 76 %>
      <p class="content"><%= post.content.slice(0..75) %>...</p>
    <% else %>
      <p class="content"><%= post.content.slice(0..75) %></p>
    <% end %>
    <a href="/posts/<%= post.id %>" class="details">詳細を見る</a>
    <div class="flex">
      <div class="comment-like">
        <span class="comment">
          <%= icon('fas', 'comment-dots') %>
          <%= post.comments.length %>
        </span>
        <span class="like">
          <%= icon('fas', 'heart') %>
          <%= post.likes.length %>
        </span>
      </div>
      <a href="/users/<%= post.user.id %>">
        <% if post.user.image? %>
          <%= image_tag post.user.image.url, alt: 'アイコン画像', width: '50', height: '50' %>
        <% else %>
          <img alt="アイコン画像" src="/assets/default.png" width="50" height="50">
        <% end %>
      </a>
    </div>
  </div>
<% end %>

app/views/posts/_search_form.html.erb
<%= form_with(url: search_posts_path, method: :get, local: true, class: 'search-form') do |f| %>
  <%= f.text_field :search, value: @search_params, placeholder: 'キーワードを入力' %>

  <button><%= icon('fas', 'search') %></button>
<% end %>

app/views/posts/_sort_menu.html.erb
<div class="sort-menu">
  <span class="menu-title">並べ替え<%= icon('fas', 'caret-down') %></span>
  <div class="sub-menu">
    <ul>
      <li><%= link_to '新着順', root_path %></li>
      <li><%= link_to 'いいね数順', popular_posts_path %></li>
    </ul>
  </div>
</div>

app/views/posts/category.html.erb
<div class="category-by">
  <div class="menu-search">
    <div class="menus">
      <%= render 'category_menu' %>
      <%= render 'sort_menu' %>
    </div>
    <%= render 'search_form' %>
  </div>
  <div class="posts">
    <%= render 'posts', posts: @posts %>
  </div>
  <%= paginate @posts %>
  <%= render 'shared/infinite_scroll1' %>
  <%= render 'shared/floating_btn' %>
</div>

app/views/posts/edit.html.erb
<% provide(:button_text, '更新する') %>
<div class="form">
  <h1>投稿を編集</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="top-page">
  <div class="menu-search">
    <div class="menus">
      <%= render 'category_menu' %>
      <%= render 'sort_menu' %>
    </div>
    <%= render 'search_form' %>
  </div>
  <div class="posts">
    <%= render 'posts', posts: @posts %>
  </div>
  <%= paginate @posts %>
  <%= render 'shared/infinite_scroll1' %>
  <%= render 'shared/floating_btn' %>
</div>

app/views/posts/new.html.erb
<% provide(:button_text, '投稿する') %>
<div class="form">
  <h1>新しい投稿</h1>
  <%= render 'form' %>
</div>

app/views/posts/popular.html.erb
<div class="popular-posts">
  <div class="menu-search">
    <div class="menus">
      <%= render 'category_menu' %>
      <%= render 'sort_menu' %>
    </div>
    <%= render 'search_form' %>
  </div>
  <div class="posts">
    <%= render 'posts', posts: @posts %>
  </div>
  <%= paginate @posts %>
  <%= render 'shared/infinite_scroll1' %>
  <%= render 'shared/floating_btn' %>
</div>

app/views/posts/search.html.erb
<div class="search-result">
  <div class="menu-search">
    <div class="menus">
      <%= render 'category_menu' %>
      <%= render 'sort_menu' %>
    </div>
    <%= render 'search_form' %>
  </div>
  <div class="posts">
    <%= render 'posts', posts: @posts %>
  </div>
  <%= paginate @posts %>
  <%= render 'shared/infinite_scroll1' %>
  <%= render 'shared/floating_btn' %>
</div>

app/views/posts/show.html.erb
<div class="post-details">
  <div class="post">
    <span class="category category-color<%= @post.category.id %>"><%= @post.category.name %></span>
    <% if @post.status == 0 %>
      <div class="private">
        <span>非公開</span>
      </div>
    <% end %>
    <% if current_user?(@post.user) %>
      <% if @post.check == 1 %>
        <h2 class="title"><i class="fas fa-star"></i><%= @post.title %></h2>
      <% else %>
        <h2 class="title"><%= @post.title %></h2>
      <% end %>
    <% else %>
      <h2 class="title"><%= @post.title %></h2>
    <% end %>
    <p class="content"><%= safe_join(@post.content.split("\n"),tag(:br)) %></p>
    <span class="created-at"><%= l @post.created_at %></span>
    <div class="flex">
      <div class="left">
        <div id="post-like-<%= @post.id %>">
          <%= render 'likes/post_like', post: @post %>
        </div>
        <% if current_user?(@post.user) %>
          <%= link_to '編集する', edit_post_path(@post), class: 'edit' %>
          <%= link_to '削除する', @post, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'delete' %>
        <% end %>
      </div>
      <div class="right">
        <a href="/users/<%= @post.user.id %>">
          <% if @post.user.image? %>
            <%= image_tag @post.user.image.url, alt: 'アイコン画像', width: '50', height: '50' %>
          <% else %>
            <img alt="アイコン画像" src="/assets/default.png" width="50" height="50">
          <% end %>
        </a>
        <%= link_to @post.user.name, @post.user, class: 'contributor' %>
      </div>
    </div>
  </div>

  <div class="form">
    <%= form_with(model: @comment) do |f| %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <div class="form-parts">
        <%= f.text_area :content, rows: '4', placeholder: 'コメントを書く' %>
        <p class="error-message"></p>
      </div>
      <button class="btn m-btn submit">コメントする<i class="fas fa-paper-plane"></i></button>
    <% end %>
  </div>

  <h2 class="comment-list">コメント一覧</h2>
  <div class="sort-menu comment-sort">
    <span class="menu-title">並べ替え<%= icon('fas', 'caret-down') %></span>
    <div class="sub-menu">
      <ul>
        <li><%= link_to '新着順', post_path(@post), remote: true %></li>
        <li><%= link_to 'いいね数順', comment_like_sort_path(post_id: @post.id), remote: true %></li>
      </ul>
    </div>
  </div>
  <div class="ajax">
    <div class="comments">
      <% @comments.each do |comment| %>
        <div class="comment" id="comment-<%= comment.id %>">
          <a href="/users/<%= comment.user.id %>">
            <% if comment.user.image? %>
              <%= image_tag comment.user.image.url, alt: 'アイコン画像', width: '50', height: '50' %>
            <% else %>
              <img alt="アイコン画像" src="/assets/default.png" width="50" height="50">
            <% end %>
          </a>
          <div class="right">
            <%= link_to comment.user.name, comment.user, class: 'commenter' %>
            <span class="created-at"><%= l comment.created_at %></span>
            <p class="content"><%= safe_join(comment.content.split("\n"),tag(:br)) %></p>
            <div id="comment-like-<%= comment.id %>" class="comment-like">
              <%= render 'likes/comment_like', comment: comment %>
            </div>
            <% if current_user?(comment.user) %>
              <%= link_to '削除する', comment, method: :delete, data: { confirm: '本当に削除しますか？' }, remote: true, class: 'delete' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @comments %>
    <%= render 'shared/infinite_scroll1' %>
  </div>
</div>

app/views/posts/show.js.erb
$(".ajax").html("<%= j(render 'shared/comments') %>");

$(".comments").infiniteScroll({
  path: ".pagination a[rel='next']",
  append: ".comment",
  history: false,
  button: ".vmb1",
  scrollThreshold: false,
  status: ".pls1",
});

if (!$(".pagination").length) {
  $(".view-more-button").hide();
}