config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/guest_login', to: 'sessions#guest'
  delete '/logout', to: 'sessions#destroy'
  get '/posts/category/:id', to: 'posts#category', as: 'posts_category'
  get '/posts/popular', to: 'posts#popular', as: 'popular_posts'
  get '/posts/search', to: 'posts#search', as: 'search_posts'
  post '/post/like/:id', to: 'likes#post_create', as: 'post_like'
  delete '/post/unlike/:id', to: 'likes#post_destroy', as: 'post_unlike'
  post '/comment/like/:id', to: 'likes#comment_create', as: 'comment_like'
  delete '/comment/unlike/:id', to: 'likes#comment_destroy', as: 'comment_unlike'
  get '/comment/like/sort', to: 'comments#like_sort', as: 'comment_like_sort'
  resources :users
  resources :posts, except: %i[index]
  resources :relationships, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
end

app/views/layouts/_footer.html.erb
<footer>
  <p>Copyright ©︎ THANKS All Rights Reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1><%= link_to 'THANKS', root_path %></h1>
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <nav>
    <ul>
      <% if logged_in? %>
        <li><%= link_to '投稿する', new_post_path %></li>
        <li><%= link_to 'マイページ', current_user %></li>
        <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to '登録する', new_user_path %></li>
        <li><%= link_to 'ログイン', login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thanks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js"></script>
  </body>
</html>